name: Automated Content Generation

on:
  schedule:
    # Генерация постов 4 раза в день (UTC время)
    # Московское время = UTC + 3 часа
    - cron: '0 5 * * *'   # 8:00 МСК
    - cron: '0 9 * * *'   # 12:00 МСК
    - cron: '0 13 * * *'  # 16:00 МСК
    - cron: '0 17 * * *'  # 20:00 МСК
    
  workflow_dispatch: # Ручной запуск

jobs:
  generate-post:
    name: Generate and Publish Post
    runs-on: ubuntu-latest
    
    steps:
      - name: Call API to generate post
        run: |
          echo "🚀 Генерация поста..."
          
          HTTP_CODE=$(curl -s -o /tmp/response.json -w "%{http_code}" \
            -X POST https://zen-automation-production.up.railway.app/api/v1/generate)
          
          echo "📊 HTTP Status: $HTTP_CODE"
          
          if [ -f /tmp/response.json ]; then
            cat /tmp/response.json
          fi
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Пост успешно опубликован!"
          else
            echo "❌ Ошибка: HTTP $HTTP_CODE"
            exit 1
          fi
